language: perl
perl:
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
notifications:
    recipients:
        - mirko@westermeier.de
    email:
        on_success: always
        on_failure: always
