#!/usr/bin/env perl

use strict;
use warnings;

use FindBin '$Bin';
use lib "$Bin/lib";

use PerLisp;

# init
my $pl = PerLisp->new->init;

# perlisp files from command line
foreach my $filename (@ARGV) {
    
    # filter
    next unless -e -r $filename;

    # load
    $pl->eval("(load \"$filename\")");
}

# read eval print loop
print "Hi, this is PerLisp.\n";
$pl->read_eval_print_loop;
print "Done.\n";

__END__
